name: Upload Artifact

on:
  workflow_run:
    workflows: ["CI Java"]  # Nome do workflow principal
    types:
      - completed  # Define que o workflow ser√° executado quando o workflow "CI Java" terminar

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Files
        uses: actions/download-artifact@v3
        with:
          name: java-build-files  # Nome do artefato salvo no workflow principal

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: java-artifact
          path: java/java-pipelines/target/*.jar